//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomControllerConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomControllerConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room absolute humidity g/m3.
        /// </summary>
        public static string ___Actual_room_absolute_humidity_g_m3__ {
            get {
                return ResourceManager.GetString("___Actual_room_absolute_humidity_g_m3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room CO2 concentration ppm.
        /// </summary>
        public static string ___Actual_room_CO2_concentration_ppm__ {
            get {
                return ResourceManager.GetString("___Actual_room_CO2_concentration_ppm__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room CO2 VOC mix.
        /// </summary>
        public static string ___Actual_room_CO2_VOC_mix__ {
            get {
                return ResourceManager.GetString("___Actual_room_CO2_VOC_mix__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room dew point °C.
        /// </summary>
        public static string ___Actual_room_dew_point__C__ {
            get {
                return ResourceManager.GetString("___Actual_room_dew_point__C__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room enthalpy kJ/k.
        /// </summary>
        public static string ___Actual_room_enthalpy_kJ_k__ {
            get {
                return ResourceManager.GetString("___Actual_room_enthalpy_kJ_k__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room humidity %.
        /// </summary>
        public static string ___Actual_room_humidity____ {
            get {
                return ResourceManager.GetString("___Actual_room_humidity____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room temperature °C.
        /// </summary>
        public static string ___Actual_room_temperature__C__ {
            get {
                return ResourceManager.GetString("___Actual_room_temperature__C__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual room VOC %.
        /// </summary>
        public static string ___Actual_room_VOC____ {
            get {
                return ResourceManager.GetString("___Actual_room_VOC____", resourceCulture);
            }
        }
    }
}
